export const API_CTRL_DOCKER_API = '/docker-api';

export const C_DOCKER = 'docker';

export const _API_CTRL_DOCKER_API_INSTANCES = '/instances';
export const API_CTRL_DOCKER_API_INSTANCES = API_CTRL_DOCKER_API + _API_CTRL_DOCKER_API_INSTANCES;

export const _API_CTRL_DOCKER_LIST_IMAGES = '/images';
export const API_CTRL_DOCKER_LIST_IMAGES = API_CTRL_DOCKER_API + _API_CTRL_DOCKER_LIST_IMAGES;

export const _API_CTRL_DOCKER_LIST_CONTAINERS = '/containers';
export const API_CTRL_DOCKER_LIST_CONTAINERS = API_CTRL_DOCKER_API + _API_CTRL_DOCKER_LIST_CONTAINERS;
