version: '3'

networks:
  txs_docker: { }

services:

  txs_docker_postgres:
    image: postgres:11
    environment:
      POSTGRES_DATABASES: docker
      POSTGRES_USER: docker
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=200'
    networks:
      - txs_docker
